snowflake:
  user: "YOUR_SNOWFLAKE_USER"
  password: "YOUR_SNOWFLAKE_PASSWORD"
  account: "YOUR_SNOWFLAKE_ACCOUNT"
  warehouse: "YOUR_WAREHOUSE"
  database: "YOUR_DATABASE"
  schema: "YOUR_SCHEMA"

anomaly_threshold: 3
source_file: "data/source_data.csv"
raw_query: "SELECT * FROM raw_layer_table WHERE ingestion_date BETWEEN '2023-01-01' AND '2023-12-31'"
target_query: "SELECT * FROM target_table"
